### ISSUE TITLE
Turbines

### ISSUE THREAD

**Issue by KiwiHawk** [pyanodon/pyalternativeenergy#2]
### Localisation
There are two entities for each tier of Turbine. The ones that are visible when placed are missing localisation.
- hawt-turbine-mk01-hidden
- hawt-turbine-mk02-hidden
- hawt-turbine-mk03-hidden
- hawt-turbine-mk04-hidden
- multiblade-turbine-mk01-hidden
- multiblade-turbine-mk03-hidden

![image](https://user-images.githubusercontent.com/59639/168521143-86343462-9dd3-49fd-80c9-2deea5b3700b.png)

### Hidden entities
Can the entities which won't be seen in game be marked as hidden? It would be less confusing for people if both don't show up in Helmod.
- hawt-turbine-mk01
- hawt-turbine-mk02
- hawt-turbine-mk03
- hawt-turbine-mk04
- multiblade-turbine-mk01
- multiblade-turbine-mk03

![image](https://user-images.githubusercontent.com/59639/168521070-4e983a17-d4a9-45dd-bbf3-dee7424a67b3.png)

### Energy consumption

In the Electric network info screen, Turbines are listed on the Consumption side as well as Production. Numbers are correct but it's strange to see them listed under consumption. Setting the [input_flow_limit](https://wiki.factorio.com/Types/EnergySource#input_flow_limit) to "0W" on the turbine's electric energy source will prevent the turbine from being listed under Consumption.

**Also applies to:**
- vawt-turbine-mk01
- vawt-turbine-mk02
- vawt-turbine-mk03
- vawt-turbine-mk04

![image](https://user-images.githubusercontent.com/59639/168693141-040b79fd-c4b7-4792-a8d4-98ca0af75115.png)

- [x] hawt-turbine-mkxx-hidden locales
- [x] multiblade-turbine-mkxx-hidden locales
- [x] hawt-turbine-mkxx hidden marker
- [x] multiblade-turbine-mkxx hidden marker

**Comment by notnotmelon** [comment]
Fixed
