### ISSUE TITLE
Error when starting multiplayer server

### ISSUE THREAD

**Issue by TL044CN** [pyanodon/pyalternativeenergy#26]
Last few lines of Server Output:
```
factorio_server |   56.949 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "Die Mod Pyanodons Alternative Energy (1.1.9) hat einen Fehler verursacht, der nicht behoben werden kann.
factorio_server | Bitte informiere den Autor der Mod über diesen Fehler.
factorio_server |
factorio_server | Error while running event pyalternativeenergy::on_init()
factorio_server | Error when running interface function pywiki.add_section: __pycoalprocessing__/scripts/wiki/wiki.lua:114: attempt to index field 'wiki_pages' (a nil value)
factorio_server | stack traceback:
factorio_server |       __pycoalprocessing__/scripts/wiki/wiki.lua:114: in function 'add_page'
factorio_server |       __pycoalprocessing__/scripts/wiki/wiki.lua:121: in function <__pycoalprocessing__/scripts/wiki/wiki.lua:120>
factorio_server | stack traceback:
factorio_server |       [C]: in function 'call'
factorio_server |       __pyalternativeenergy__/scripts/wiki/text-pages.lua:5: in function 'on_init'
factorio_server |       __pyalternativeenergy__/control.lua:16: in function <__pyalternativeenergy__/control.lua:11>"
factorio_server |   56.949 Info ServerMultiplayerManager.cpp:795: updateTick(4294967295) changing state from(CreatingGame) to(InitializationFailed)
```
Installed mods here:
.rwxrwxrwx root root 1.4 MB Fri Mar 10 22:40:53 2023 aai-programmable-structures_0.7.4.zip
.rwxrwxrwx root root 1.2 MB Sun Mar 12 18:43:05 2023 aai-programmable-vehicles_0.7.24.zip
.rwxrwxrwx root root  20 MB Fri Mar 10 22:41:34 2023 aai-signal-transmission_0.4.7.zip
.rwxrwxrwx root root 122 KB Fri Mar 10 22:40:54 2023 aai-signals_0.6.1.zip
.rwxrwxrwx root root 836 KB Fri Mar 10 22:40:55 2023 aai-vehicles-chaingunner_0.6.1.zip
.rwxrwxrwx root root 5.7 MB Fri Mar 10 22:41:01 2023 aai-vehicles-flame-tank_0.5.1.zip
.rwxrwxrwx root root 542 KB Fri Mar 10 22:41:02 2023 aai-vehicles-flame-tumbler_0.6.1.zip
.rwxrwxrwx root root 5.0 MB Fri Mar 10 22:41:10 2023 aai-vehicles-hauler_0.6.1.zip
.rwxrwxrwx root root 4.4 MB Fri Mar 10 22:41:17 2023 aai-vehicles-ironclad_0.6.8.zip
.rwxrwxrwx root root 5.6 MB Fri Mar 10 22:41:24 2023 aai-vehicles-laser-tank_0.6.4.zip
.rwxrwxrwx root root  13 MB Fri Mar 10 22:41:42 2023 aai-vehicles-miner_0.6.4.zip
.rwxrwxrwx root root 7.3 MB Fri Mar 10 22:41:48 2023 aai-vehicles-warden_0.5.3.zip
.rwxrwxrwx root root 297 KB Fri Mar 10 22:41:43 2023 aai-zones_0.6.4.zip
.rwxrwxrwx root root  67 KB Fri Mar 10 22:41:43 2023 AutoDeconstruct_0.3.7.zip
.rwxrwxrwx root root 170 KB Fri Mar 10 22:41:44 2023 big-data-string_1.0.1.zip
.rwxrwxrwx root root 152 KB Sun Mar 19 19:40:12 2023 bobinserters_1.1.7.zip
.rwxrwxrwx root root  72 KB Fri Mar 10 22:41:44 2023 Bottleneck_0.11.7.zip
.rwxrwxrwx root root  41 KB Fri Mar 10 22:41:44 2023 ChangeMapSettings_5.0.1.zip
.rwxrwxrwx root root  24 KB Fri Mar 10 22:41:44 2023 CleanFloor_1.1.0.zip
.rwxrwxrwx root root  34 KB Fri Mar 10 22:41:45 2023 clock_1.1.0.zip
.rwxrwxrwx root root 310 KB Fri Mar 10 22:41:45 2023 Clockwork_1.1.1.zip
.rwxrwxrwx root root 282 KB Fri Mar 10 22:41:46 2023 DoingThingsByHand_1.2.2.zip
.rwxrwxrwx root root 317 KB Mon Mar 13 04:52:08 2023 enemyracemanager_1.17.0.zip
.rwxrwxrwx root root  64 MB Fri Mar 10 22:43:08 2023 enemyracemanager_assets_1.0.1.zip
.rwxrwxrwx root root 3.7 MB Mon Mar 13 04:52:10 2023 erm_zerg_1.19.0.zip
.rwxrwxrwx root root 3.1 MB Fri Mar 10 22:42:05 2023 Factorissimo2_2.5.3.zip
.rwxrwxrwx root root 324 KB Fri Mar 10 22:42:06 2023 factoryplanner_1.1.60.zip
.rwxrwxrwx root root 302 KB Fri Mar 10 22:42:06 2023 FactorySearch_1.10.13.zip
.rwxrwxrwx root root 372 KB Fri Mar 10 22:42:07 2023 flib_0.12.5.zip
.rwxrwxrwx root root 2.5 MB Fri Mar 10 22:42:13 2023 FluidMustFlow_1.3.1.zip
.rwxrwxrwx root root 126 KB Fri Mar 10 22:42:13 2023 FNEI_0.4.1.zip
.rwxrwxrwx root root  13 KB Fri Mar 10 22:42:14 2023 GhostInHand_1.0.6.zip
.rwxrwxrwx root root 124 KB Fri Mar 10 22:42:14 2023 informatron_0.3.2.zip
.rwxrwxrwx root root  13 MB Fri Mar 10 22:42:44 2023 K2_Turrets_1.0.0.zip
.rwxrwxrwx root root 4.3 MB Fri Mar 10 22:42:55 2023 K2_Wireless-Charger_1.0.3.zip
.rwxrwxrwx root root 1.4 MB Fri Mar 10 22:42:58 2023 laserfence_1.1.5.zip
.rwxrwxrwx root root 573 KB Fri Mar 10 22:43:00 2023 LoaderRedux_1.8.1.zip
.rwxrwxrwx root root 450 KB Fri Mar 10 22:43:01 2023 LogisticTrainNetwork_1.18.2.zip
.rwxrwxrwx root root  56 KB Fri Mar 10 22:43:01 2023 ltn-cleanup_1.0.17.zip
.rwxrwxrwx root root 237 KB Fri Mar 10 22:43:02 2023 LTN_Combinator_Modernized_1.0.14.zip
.rwxrwxrwx root root  67 KB Fri Mar 10 22:43:03 2023 LtnManager_0.4.17.zip
.rwxrwxrwx root root  35 MB Fri Mar 10 22:44:21 2023 Mechanicus_1.0.7.zip
.rwxrwxrwx root root 162 KB Fri Mar 10 22:43:08 2023 mining-patch-planner_1.4.0.zip
.rwxrwxrwx root root 5.4 KB Sun Mar 19 20:15:58 2023 mod-list.json
.rwxrwxrwx root root  20 KB Sun Mar 19 20:16:04 2023 mod-settings.dat
.rwxrwxrwx root root 1.2 MB Fri Mar 10 22:43:10 2023 pyalienlife_2.0.10.zip
.rwxrwxrwx root root 169 MB Fri Mar 10 22:46:49 2023 pyalienlifegraphics2_2.0.4.zip
.rwxrwxrwx root root 187 MB Fri Mar 10 22:51:19 2023 pyalienlifegraphics3_2.0.3.zip
.rwxrwxrwx root root 146 MB Fri Mar 10 21:22:03 2023 pyalienlifegraphics_1.3.3.zip
.rwxrwxrwx root root 140 MB Fri Mar 10 22:49:45 2023 pyalienlifegraphics_2.0.2.zip
.rwxrwxrwx root root 410 KB Sun Mar 19 19:30:14 2023 pyalternativeenergy_1.1.9.zip
.rwxrwxrwx root root 158 MB Sun Mar 19 19:32:46 2023 pyalternativeenergygraphics_1.0.5.zip
.rwxrwxrwx root root 377 KB Fri Mar 10 22:49:46 2023 pycoalprocessing_2.0.7.zip
.rwxrwxrwx root root 124 MB Fri Mar 10 22:52:31 2023 pycoalprocessinggraphics_2.0.4.zip
.rwxrwxrwx root root 204 KB Fri Mar 10 22:51:20 2023 pyfusionenergy_2.0.4.zip
.rwxrwxrwx root root  67 MB Fri Mar 10 22:53:47 2023 pyfusionenergygraphics_2.0.0.zip
.rwxrwxrwx root root 196 KB Fri Mar 10 22:52:31 2023 pyhightech_2.0.7.zip
.rwxrwxrwx root root  91 MB Fri Mar 10 22:54:30 2023 pyhightechgraphics_2.0.1.zip
.rwxrwxrwx root root  41 MB Fri Mar 10 22:55:20 2023 pyindustry_2.0.6.zip
.rwxrwxrwx root root 235 KB Fri Mar 10 22:54:31 2023 pypetroleumhandling_2.1.5.zip
.rwxrwxrwx root root  88 MB Fri Mar 10 22:56:19 2023 pypetroleumhandlinggraphics_2.0.0.zip
.rwxrwxrwx root root 201 KB Sun Mar 19 19:30:27 2023 pypostprocessing_0.2.4.zip
.rwxrwxrwx root root 316 KB Fri Mar 10 22:55:22 2023 pyrawores_2.4.7.zip
.rwxrwxrwx root root 109 MB Fri Mar 10 22:57:46 2023 pyraworesgraphics_2.0.1.zip
.rwxrwxrwx root root 8.1 MB Fri Mar 10 22:56:30 2023 RealisticReactors_3.1.4.zip
.rwxrwxrwx root root 581 KB Fri Mar 10 22:56:31 2023 shield-generators_0.3.5.zip
.rwxrwxrwx root root 645 KB Fri Mar 10 22:56:33 2023 SmartTrains_5.1.1.zip
.rwxrwxrwx root root  39 KB Fri Mar 10 22:56:33 2023 Squeak Through_1.8.2.zip
.rwxrwxrwx root root 373 KB Fri Mar 10 21:22:55 2023 stdlib_1.4.6.zip
.rwxrwxrwx root root 146 KB Fri Mar 10 22:56:33 2023 stdlib_1.4.8.zip
.rwxrwxrwx root root  49 KB Fri Mar 10 22:56:33 2023 Todo-List_19.3.0.zip
.rwxrwxrwx root root 163 KB Fri Mar 10 22:56:34 2023 train-log_1.1.6.zip
.rwxrwxrwx root root 1.1 MB Fri Mar 10 22:56:36 2023 train-trails_0.0.11.zip
.rwxrwxrwx root root 545 KB Fri Mar 10 22:56:36 2023 vanilla-loaders-hd_1.1.12.zip
.rwxrwxrwx root root  50 KB Fri Mar 10 22:56:37 2023 VehicleSnap_1.18.5.zip
.rwxrwxrwx root root 3.9 MB Fri Mar 10 22:56:42 2023 Warehousing_0.5.7.zip
.rwxrwxrwx root root  60 KB Fri Mar 10 22:56:43 2023 Waterfill_v17_1.1.0.zip
.rwxrwxrwx root root 3.7 KB Mon Mar 13 13:23:08 2023 zerm_postprocess_1.1.0.zip

**Comment by notnotmelon** [comment]
Fixed. Thanks for the report.
