### ISSUE TITLE
Thorium reactors duplicate molten salt; recipe is off by a factor of 10.

### ISSUE THREAD

**Issue by hallucinogender** [pyanodon/pyalternativeenergy#31]
The standard nuclear reactor cycle consumes **molten salt** and outputs **spent reactor fuel** and neutrons. The spent reactor fuel is then processed with lithium peroxide to yield **hot molten salt**, a lithium byproduct which can be reprocessed to close the lithium loop, and high energy waste for the purex chain. This standard recipe is fine, because you receive exactly as much molten salt as you input - molten salt is a closed loop.

The problem is that the **Molten fluoride with Pa-233** recipe (the one that consumes molten fluoride with thorium) gets the ratio wrong. As established with the standard recipe, every 100 units of molten salt fed into a nuclear reactor must yield 1 unit of spent reactor fuel, which is processed to retrieve 100 units of hot molten salt. With the thorium recipe, every 100 units of molten salt fed into the nuclear reactor yields 10 units of spent reactor fuel, which is processed into 1000 units of hot molten salt. Instead of a closed loop, a thorium reactor duplicates enormous quantities of molten salt.

To fix this, either multiply the molten salt input in the **Molten fluoride with Pa-233** recipe by 10, or divide the spent reactor fuel output of that recipe by 10.

**Comment by notnotmelon** [comment]
Fixed. Thanks for the report. https://github.com/pyanodon/pyalternativeenergy/commit/ddebcf558603f4e4735f6457cbd870c24800a042
